In [9]:
import numpy as np 
n=np.array([[1,2,3,-3]])
print(np.transpose(n))

[[ 1]
 [ 2]
 [ 3]
 [-3]]


In [15]:
#Ejeciocio 
a= np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print('')
b=np.array([[-3],[5],[-2]])


print(np.transpose(b))
print(b)
x=np.linalg.solve(a,b)
print(x)


[[-3  5 -2]]
[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]
