In [14]:
import numpy as np 
n= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print('')
print(np.amin(n,0))  #buscar valor min en columna 
print(np.amin(n,1)) #buscar valor min en fila

print(np.ptp(n, axis=1)) #Obtener rangos 


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]
[1 4 7]
[2 2 2]


In [16]:
#Perceptiles
print(np.percentile(n,50, axis=1))

[2. 5. 8.]


In [20]:
#mediana 
n= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)
print(np.median(n, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]


In [24]:
#media aritmetica
print(np.mean(n))


5.0
5.0


In [26]:
#Promedio penderado
print(np.average(n))


5.0


In [27]:
#Desviacion estandar 

print(np.std(n))

2.581988897471611
