In [40]:
#Funciones en matrices
import numpy as np 

rangos = np.arange(50).reshape(10,5)
print(rangos.shape)#para saber cuantas filas y cuantas columnas tiene un rango
print(rangos.ndim)#saber las dimenciones de una matriz
print(rangos.size)#saber cuantos elementos hay en una mtriz 


(10, 5)
2
50


In [41]:
#Generar matriz de solo zeros 
zero=np.zeros((2,2))
print(zero)


[[0. 0.]
 [0. 0.]]


In [42]:
#Generar matrices aleatorias y rapidas 

notas=np.linspace(99,70,30).reshape(3,10)
print(notas)

[[99. 98. 97. 96. 95. 94. 93. 92. 91. 90.]
 [89. 88. 87. 86. 85. 84. 83. 82. 81. 80.]
 [79. 78. 77. 76. 75. 74. 73. 72. 71. 70.]]


In [25]:
#Matrices de tres dimenciones

tresdimenciones=np.arange(27).reshape(3,3,3)
print(tresdimenciones)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [46]:
#Ordenar los datos de menor a mayor 
nm= np.array([121,2,3,7,5,4,8])
print(np.sort(nm))


[  2   3   4   5   7   8 121]


In [49]:
#Elevar un array
Elevado= np.array([1,2,3])
print(np.power(Elevado,3))

[ 1  8 27]


In [50]:
m1=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array(m1>=4))

[False False False  True  True  True  True  True  True  True]


In [51]:
foorr=np.array([1,2,3,4,5])
for i in foorr:
    print(i)

1
2
3
4
5


In [53]:
#Valor maximo
m1=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array(m1.max()))

#Valor minimo 
m1=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array(m1.min()))

10
1


In [55]:
#Combinar dos matrices
m1=np.array([234,23,23,23,23,234,23,234,55,10])
m2=np.array([123,2123,3324,443,52,64,72,84,93,120])
print(np.concatenate((m1,m2)))


[ 234   23   23   23   23  234   23  234   55   10  123 2123 3324  443
   52   64   72   84   93  120]


In [59]:
m1=np.array([[1,2],[1,2]])
m2=np.array([[1,5],[7,2]])

print(m1+10)

[[11 12]
 [11 12]]


In [61]:
m1=np.array([1,2])
print(np.divide(m1,m2))

[[1.         0.4       ]
 [0.14285714 1.        ]]


In [62]:
print(m1.dot(m2))

[15  9]
