In [27]:
import numpy as np
#Generar numeros aleatorios enteros
m=np.random.randint(10, size=(3,3))
m

array([[5, 9, 7],
       [0, 6, 8],
       [9, 4, 1]])

In [36]:
#generear numeros aleatorios con docimales 
nj=np.random.rand(5,5)
nj
#Seleccionar uno o mas valores aleatorio dentro de la matriz
mk=np.random.choice([2,3,4,6,3,4,5,3,3,1,3,1],size =(3,4))
print(mk)

[[1 6 1 1]
 [4 1 3 4]
 [3 3 3 3]]


In [47]:
matriz=np.random.choice([2,4,8,10], p=[0.3,0.3,0.3,0.1], size=[50])
print(  matriz)

[ 8  4  4  4  8 10 10  2  4  2  2  8  8  2  4  2  4  8  2  2  2  2  4  4
  2  8  2  4  4  4  4  4  2  8  4  8  8  8  2  4  2  4  8  4  8  2  2  2
  2  4]
