In [14]:
import numpy as np 

matriz=np.array([1,2,3,4,5,6])
matriz= matriz + np.array([10])
print(matriz)

[11 12 13 14 15 16]


In [20]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(a+b)
a*b


[2 4 6]


array([1, 4, 9])

In [1]:
print(np.random.rand(10))


NameError: name 'np' is not defined

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk


In [13]:

array=np.array([1,2,3,4,5,6,7])
array2=np.array([8,2,3,4,5,5,2])
array=array+array2
print(array)

[ 9  4  6  8 10 11  9]


In [16]:
matriz=np.array([1,2,3,4,5,6])
matriz


array([1, 2, 3, 4, 5, 6])

In [20]:
matriz2d=np.array([[1,2,3], [4,5,6]]) #Generar una matriz en 2D
matriz2d

lista= [1,2,3,4,5,6,7,8,9,10]
matriz1=np.array(lista)
print(matriz1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [22]:
#Crear matrices de 2 dimenciones con listas

lista=[[1,2,3],[4,5,6],[7,8,9]]
array=np.array(lista)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
#Crear una matriz con rangos
rangos=np.arange(20).reshape(4,5)
print(rangos)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
